# Generated by Django 4.2.7 on 2023-11-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='xuanze',
        ),
        migrations.AlterModelTable(
            name='question',
            table='wenti',
        ),
    ]
